- hosts: localhost
  gather_facts: yes
  vars:
    testvar: hello
  tasks:
    - debug:
        msg: "{{ testvar }}"
    - debug:
        msg: "{{ hostvars[inventory_hostname].keys() }}"
    - debug:
        msg: "{{ hostvars[inventory_hostname]['gitconfig'].repo() }}"
      with_items: "{{ gitconfig }}"
