---
- hosts: all
  tasks:
    - name: Distribute Configuration File
      copy:
        src: "../files/.gitconfig"
        dest: "~/.gitconfig"
        owner: "dsturm" 
        state: present
        mode: 0664
