---
- hosts: all
  gather_facts: yes
  tasks:
    - name: Checking Repository Destinations
      file:
        path: ~/git/{{ hostvars['inventory_hostname']['gitconfig']['name'] }}
        state: directory
#      with_items: 
#        - "{{ hostvars[ansible_host]['gitconfig'] }}"

    - name: Loading and Updating Repositories
      git:
        repo: "{{ hostvars['inventory_hostname']['gitconfig']['repo'] }}"
        dest: ~/git/{{ hostvars['inventory_hostname']['gitconfig']['name'] }}
        clone: yes
        update: yes
#      with_items: 
#        - "{{ hostvars[['gitconfig'] }}"
