---
- hosts: all
  tasks:
    - name: Checking Repository Destinations
      file:
        path: ~/git/{{ item.name }}
        state: directory
      with_items: "{{ hostvars[gitconfig] }}"

    - name: Loading and Updating Repositories
      git:
        repo: "{{ item.repo }}"
        dest: ~/git/{{ item.name }}
        clone: yes
        update: yes
      with_items: "{{ hostvars[gitconfig] }}"
