---
- hosts: all
  gather_facts: yes
  tasks:
    - name: Checking Repository Destinations
      file:
        path: ~/git/{{ hostvars['gitconfig']['name'] }}
        state: directory
#      with_items: hostvars[gitconfig]

    - name: Loading and Updating Repositories
      git:
        repo: "{{ hostvars['gitconfig']['repo'] }}"
        dest: ~/git/{{ hostvars['gitconfig']['name'] }}
        clone: yes
        update: yes
#      with_items: hostvars[gitconfig]
