---
- hosts: all
  tasks:
    - name: Checking Repository Destinations
      file:
        path: ~/git/{{ name }}
        state: directory

    - name: Loading and Updating Repositories
      git:
        repo: "{{ repo }}"
        dest: ~/git/{{ name }}
        clone: yes
        update: yes
      with_items: "{{ gitconfig }}"
