---
- hosts: all
  tasks:
    - name: Checking Repository Destinations
      file:
        path: ~/git/{{ hostvars[item.name] }}
        state: directory
#      with_items: "{{ gitconfig }}"

    - name: Loading and Updating Repositories
      git:
        repo: "{{ hostvars[item.repo] }}"
        dest: ~/git/{{ hostvars[item.name] }}
        clone: yes
        update: yes
#      with_items: "{{ gitconfig }}"
