---
- hosts: all
  tasks:
    - name: Checking Repository Destinations
      file:
        path: ~/git/{{ gitconfig.name }}
        state: directory
      with_items: "{{ gitconfig }}"
      
    - name: Loading and Updating Repositories
      git:
        repo: "{{ gitconfig.repo }}"
        dest: ~/git/{{ gitconfig.name }}
        clone: yes
        update: yes
      with_items: "{{ gitconfig }}"
