---
- hosts: all
  gather_facts: yes
  tasks:
    - name: Checking Repository Destinations
      file:
        path: ~/git/{{ hostvars.host.gitconfig.name }}
        state: directory
#      with_items: 
#        - "{{ hostvars[ansible_host]['gitconfig'] }}"

    - name: Loading and Updating Repositories
      git:
        repo: "{{ hostvars.host.gitconfig.repo }}"
        dest: ~/git/{{ hostvars.host.gitconfig.name }}
        clone: yes
        update: yes
#      with_items: 
#        - "{{ hostvars[['gitconfig'] }}"
